package lesson34.entity;
// Generated 13 Mar 2023, 17:53:22 by Hibernate Tools 4.3.5.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "employees", catalog = "classicmodels")
public class Employee {

    private int employeeNumber;
    private Employee employee;
    private Office office;
    private String lastName;
    private String firstName;
    private String extension;
    private String email;
    private String jobTitle;
    private Set<Employee> employees = new HashSet<>(0);
    private Set<Customer> customers = new HashSet<>(0);

    public Employee() {
    }

    public Employee(int employeeNumber, Office office, String lastName, String firstName, String extension,
            String email, String jobTitle) {
        this.employeeNumber = employeeNumber;
        this.office = office;
        this.lastName = lastName;
        this.firstName = firstName;
        this.extension = extension;
        this.email = email;
        this.jobTitle = jobTitle;
    }

    public Employee(int employeeNumber, Employee employee, Office office, String lastName, String firstName,
            String extension, String email, String jobTitle, Set<Employee> employees, Set<Customer> customer) {
        this.employeeNumber = employeeNumber;
        this.employee = employee;
        this.office = office;
        this.lastName = lastName;
        this.firstName = firstName;
        this.extension = extension;
        this.email = email;
        this.jobTitle = jobTitle;
        this.employees = employees;
        this.customers = customer;
    }

    @Id

    @Column(name = "employeeNumber", unique = true, nullable = false)
    public int getEmployeeNumber() {
        return this.employeeNumber;
    }

    public void setEmployeeNumber(int employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reportsTo")
    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "officeCode", nullable = false)
    public Office getOffice() {
        return this.office;
    }

    public void setOffice(Office office) {
        this.office = office;
    }

    @Column(name = "lastName", nullable = false, length = 50)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "firstName", nullable = false, length = 50)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "extension", nullable = false, length = 10)
    public String getExtension() {
        return this.extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    @Column(name = "email", nullable = false, length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "jobTitle", nullable = false, length = 50)
    public String getJobTitle() {
        return this.jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
    public Set<Employee> getEmployees() {
        return this.employees;
    }

    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
    public Set<Customer> getCustomers() {
        return this.customers;
    }

    public void setCustomers(Set<Customer> customer) {
        this.customers = customer;
    }

    @Override
    public String toString() {
        return "Employee [employeeNumber=" + employeeNumber + ", lastName=" + lastName
                + ", firstName=" + firstName + ", extension=" + extension + ", email=" + email + ", jobTitle="
                + jobTitle + "]";
    }

}
