package lesson34.entity;
// Generated 13 Mar 2023, 17:53:22 by Hibernate Tools 4.3.5.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Productlines generated by hbm2java
 */
@Entity
@Table(name = "productlines", catalog = "classicmodels")
public class Productline {

    private String productLine;
    private String textDescription;
    private String htmlDescription;
    private byte[] image;
    private Set<Product> product = new HashSet<>(0);

    public Productline() {
    }

    public Productline(String productLine) {
        this.productLine = productLine;
    }

    public Productline(String productLine, String textDescription, String htmlDescription, byte[] image,
            Set<Product> product) {
        this.productLine = productLine;
        this.textDescription = textDescription;
        this.htmlDescription = htmlDescription;
        this.image = image;
        this.product = product;
    }

    @Id

    @Column(name = "productLine", unique = true, nullable = false, length = 50)
    public String getProductLine() {
        return this.productLine;
    }

    public void setProductLine(String productLine) {
        this.productLine = productLine;
    }

    @Column(name = "textDescription", length = 4000)
    public String getTextDescription() {
        return this.textDescription;
    }

    public void setTextDescription(String textDescription) {
        this.textDescription = textDescription;
    }

    @Column(name = "htmlDescription", length = 16777215)
    public String getHtmlDescription() {
        return this.htmlDescription;
    }

    public void setHtmlDescription(String htmlDescription) {
        this.htmlDescription = htmlDescription;
    }

    @Column(name = "image")
    public byte[] getImage() {
        return this.image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "productline")
    public Set<Product> getProducts() {
        return this.product;
    }

    public void setProducts(Set<Product> product) {
        this.product = product;
    }

}
